name: given_when_then
description: A Flutter package to enable code reuse while making tests more readable.
version: 0.3.0
homepage: https://github.com/fatherOfLegends/given_when_then
repository: https://github.com/fatherOfLegends/given_when_then
issue_tracker: https://github.com/fatherOfLegends/given_when_then/issues

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter